### ISSUE TITLE
Present your work so far to Scott

### ISSUE THREAD

**Issue by JBB** [cs210/vmware#21]
Hi team, 

I talked with Scott this week and it doesn't sound like you've been keeping him abreast of your progress.  I recommend scheduling a meeting with him at your earliest convenience to share your progress.  If it is easier and more sustainable you can also keep him updated with asynchronous updates in some form that is convenient for you.  Either way, a good goal is to turn him into a champion for your solution.

Jay

**Comment by Sidu28** [comment]
Hi!
As most of our developments happened during week 10, we were unable to meet with Scott before the final presentations.  However, we have reached out for a meeting this week to get him up to speed!
Sincerely,
Siddhartha
