### ISSUE TITLE
--file=[FILENAME] triggers command line argument error

### ISSUE THREAD

**Issue by kevinwho777** [cs210/vmware#46]
It may just be my problem, I am currently doing: --file="files/good/filename" where "files" is a subdirectory of data

**Comment by mananshah99** [comment]
What's the error trace?

**Comment by kevinwho777** [comment]
usage: main.py [-h] [--file FILE] [--dir DIR] [--label LABEL] [--good GOOD]
               [--bad BAD] [--n N]
main.py: error: check your command line arguments

I am still getting all of the features printed just fine

**Comment by kevinwho777** [comment]
Okay i found the fix -- doesn't affect anything tho, i'll include it in the next PR
