### ISSUE TITLE
Return an error message when 'analyze' button is pressed 

### ISSUE THREAD

**Issue by jangj8523** [cs210/vmware#61]
When I pressed `analyze` button on an empty PE file, the website did not return a popup box how to handle the situation. Refreshing the page is definitely the likely option but I may have been one of the rare few who got confused with what was happening. 

![Screen Shot 2021-05-05 at 3 54 20 AM](https://user-images.githubusercontent.com/10877219/117055586-4a48a680-ad56-11eb-90c3-5f2f10704079.png)

**Comment by mananshah99** [comment]
Yes, the analyze button is only intended to be pressed when a file has been uploaded. Working on a better message to that effect.

**Comment by mananshah99** [comment]
Yes, the analyze button is only intended to be pressed when a file has been uploaded. Working on a better message to that effect.
